"""
Pydantic schemas for question generation API operations.

These schemas provide type safety and automatic OpenAPI documentation.
Questions are transient (response-only) until Ollama integration in next phase.
"""

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict


class GenerateQuestionsRequest(BaseModel):
    """Request schema for generating questions from videos."""
    
    video_ids: List[str] = Field(
        min_length=1,
        description="List of YouTube video IDs to generate questions from"
    )
    question_count: int = Field(
        default=10,
        ge=1,
        le=50,
        description="Number of questions to generate (1-50)"
    )
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "video_ids": ["abc123", "xyz789"],
                "question_count": 10
            }
        }
    )


class GeneratedQuestion(BaseModel):
    """
    Intermediate schema for questions generated by providers.
    
    This is used by question generation providers (Ollama, OpenRouter)
    before questions are saved to the database.
    """
    
    video_id: str
    question_text: str
    answer: Optional[str] = None
    context: Optional[str] = None
    difficulty: Optional[str] = None
    question_type: Optional[str] = None


class QuestionResponse(BaseModel):
    """Response schema for a single generated question."""
    
    id: int
    generation_id: int
    video_id: str
    question_text: str
    answer: Optional[str] = None
    context: Optional[str] = None
    difficulty: Optional[str] = None
    question_type: Optional[str] = None
    order_index: int
    created_at: datetime
    updated_at: datetime
    
    model_config = ConfigDict(from_attributes=True)


class QuestionGenerationResult(BaseModel):
    """Per-video generation result returned by the generate endpoint."""
    
    video_id: str
    status: str  # One of: "success", "no_transcription", "failed"
    message: str
    questions: Optional[List[QuestionResponse]] = None
    error: Optional[str] = None
    question_count: int = 0


class GenerateQuestionsResponse(BaseModel):
    """Wrapper for batch question generation results with summary statistics."""
    
    results: List[QuestionGenerationResult]
    total: int
    successful: int
    failed: int
    no_transcription: int
    total_questions: int
    generation_id: Optional[int] = None


class UpdateQuestionRequest(BaseModel):
    """Request schema for updating a question."""
    
    question_text: Optional[str] = None
    answer: Optional[str] = None
    context: Optional[str] = None
    difficulty: Optional[str] = None
    question_type: Optional[str] = None
    order_index: Optional[int] = None


class UpdateQuestionsOrderRequest(BaseModel):
    """Request schema for reordering questions."""
    
    question_ids: List[int] = Field(
        min_length=1,
        description="Ordered list of question IDs"
    )
